sudo: required
dist: trusty

language: java
jdk:
  - oraclejdk8

install: true
script: ./gradlew build

notifications:
  email: false

before_install:
  - git config --global user.name "Lapislazuli"
  - git config --global user.email "lapislazuli@lapis.blue"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
